### ISSUE TITLE
Cannot use button or input tag in file-upload component

### ISSUE THREAD

**Issue by scottwernervt** [tim-evans/ember-file-upload#16] opened 2016-10-18 14:53 UTC
Is there a reason why `button` and `input` are not valid tags for `file-uploader` component?

``` javascript
# _ember-file-upload/addon/components/file-upload/component.js
const VALID_TAGS = ['a', 'abbr', 'area', 'audio', 'b', 'bdo', 'br', 'canvas', 'cite',
                    'code', 'command', 'datalist', 'del', 'dfn', 'em', 'embed', 'i',
                    'iframe', 'img', 'kbd', 'mark', 'math', 'noscript', 'object', 'q',
                    'ruby', 'samp', 'script', 'small', 'span', 'strong', 'sub', 'sup',
                    'svg', 'time', 'var', 'video', 'wbr'];
```

**Repeat Issue (use example on readme)**

``` handlebars
{{#file-upload queue=(file-queue for="photos")}}
    <button class="button-primary" id="upload-image" tabindex=0>Add an Image.</button>
    {{!--<input type="file" class="button-primary" id="upload-image" tabindex=0>--}}
{{/file-upload}}
```

> Uncaught Error: Assertion Failed: "<button class="button-primary" id="upload-image" tabindex="0">Add an Image.</button>" is not allowed as a child of {{file-upload}}.

**Comment by tim-evans** [comment] 2016-10-18 18:45
Buttons and inputs are illegal children of `<label>`s  :/

**Comment by tim-evans** [comment] 2016-10-18 19:18
(Well, not inputs, I exclude them since there's a hidden input in the field anyways)

**Comment by thedig** [comment] 2016-10-18 22:29
Is this library then intended to only implement drag/drop upload and not a button-based input field?

**Comment by chrisdpeters** [comment] 2017-02-02 02:49
To potentially clarify, it seems that the buttons in the examples don't work in IE11. (Works fine in Chrome and Firefox though.)

I'm wondering if this is related to some hackery I can remember doing on another project where I had to position an invisible `<input type="file">` element over the label so that even though the user thought they were clicking the label-styled-as-button, they were actually clicking the invisible input.

**Comment by tim-evans** [comment] 2017-02-02 19:25
@chrisdpeters exactly correct! I find that the label-styled-as-button is a better way to do this than the invisible input positioned over the input. It tends to get out of sync from page from time to time

**Comment by tim-evans** [comment] 2017-02-02 19:27
Button based fields are totally valid, just not actually `button` elements. I think it's a small concession to disallow `button` elements for the stability of the component.

**Comment by chrisdpeters** [comment] 2017-02-03 03:13
The example in the README uses an `<a>` tag as the thing to click:

```hbs
{{#file-upload name="photos"
               accept="image/*"
               multiple=true
               onfileadd=(route-action "uploadImage")}}
  <a id="upload-image" tabindex=0>Add an Image.</a>
{{/file-upload}}
```

That doesn't seem to work in Internet Explorer. When I change it to a `<span>` (which I'm styling to look like a button), it works:

```hbs
{{#file-upload name="photos"
               accept="image/*"
               multiple=true
               onfileadd=(route-action "uploadImage")}}
  <span id="upload-image" tabindex=0>Add an Image.</span>
{{/file-upload}}
```

**Comment by tim-evans** [comment] 2017-02-03 15:44
Ooops, will remove from README 🙊

**Comment by tim-evans** [comment] 2017-02-03 15:53
But it *should* work, according to spec. But blah, IE.

**Comment by tim-evans** [comment] 2017-02-03 15:54
Hmm. Maybe a solution is to have a config to whitelist IE support, that way we can support either end.

**Comment by adamreisnz** [comment] 2017-08-08 23:54
Same problem with a `div` or a `figure`

**Comment by tim-evans** [comment] 2017-08-09 03:05
@adamreisnz this is spec related to HTML:

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/label

| Permitted content | [Phrasing content](https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Content_categories#Phrasing_content), but no descendant label elements. No labelable elements other than the labeled control are allowed.
-- | --

Elements that are Phrasing content are:

`<abbr>`, `<audio>`, `<b>`, `<bdo>`, `<br>`, `<button>`, `<canvas>`, `<cite>`, `<code>`,  `<data>`, `<datalist>`, `<dfn>`, `<em>`, `<embed>`, `<i>`, `<iframe>`, `<img>`, `<input>`, `<kbd>`, `<label>`, `<mark>`, `<math>`, `<meter>`, `<noscript>`, `<object>`, `<output>`, `<progress>`, `<q>`, `<ruby>`, `<samp>`, `<script>`, `<select>`, `<small>`, `<span>`, `<strong>`, `<sub>`, `<sup>`, `<svg>`, `<textarea>`, `<time>`, `<var>`, `<video>`, `<wbr>`

**Comment by tim-evans** [comment] 2017-08-09 03:11
So, this isn't a bug, just a side-effect of restrictions in browsers.

For these buttons to work properly and without introducing an extraordinary amount of code to make a hidden input appear over DOM whilst propagating cursor events, this is the best solution I've found. There is one issue with IE support here, which could use some love, but I think that deserves a separate issue.

I'm closing this issue, since it's expected behavior and it actually lets you know before that your HTML will not work (reliably) due to it being invalid according to the W3C.

**Closed by tim-evans** 2017-08-09 03:11 UTC

**Comment by mhluska** [comment] 2018-01-10 04:57
@tim-evans why not just allow any elements and let the developer decide whether he wants to follow the spec or not? I've never seen a spec be enforced at the library level that even the browser doesn't strictly enforce.

**Comment by tim-evans** [comment] 2018-01-10 18:16
Hi @mhluska I'm trying to prevent developers from shooting themselves in the foot with this. Glimmer actually does a bunch of HTML5 validation for us, I would say it's a nice to have.

(As a side note, I would appreciate if you didn't use gendered pronouns when talking about the user base 😄 )

**Comment by mhluska** [comment] 2018-01-11 01:55
@tim-evans I'd appreciate if you didn't use the term "shooting themselves in the foot". It offends those of us that got shot in the foot, myself included.

In all seriousness though, feel free to censor me - it's your repo.
